In [12]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
stock_list = [3.5, 5, 2, 8, 4.2]

In [14]:
returns = np.array(stock_list)
print (returns, type(returns))

[3.5 5.  2.  8.  4.2] <class 'numpy.ndarray'>


In [15]:
A = np.array([[1, 2], [3, 4]])
print (A, type(A))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [16]:
print (A.shape)

(2, 2)


In [17]:
print (np.log(returns))

[1.25276297 1.60943791 0.69314718 2.07944154 1.43508453]


In [18]:
print (np.mean(returns))


4.54


In [20]:
print (np.max(returns))

8.0


In [22]:
print ("Mean: ", np.mean(returns), "Std Dev: ", np.std(returns))

Mean:  4.54 Std Dev:  1.9915822855207364


In [29]:
N = 10
assets = np.zeros((N, 100))
returns = np.zeros((N, 100))

In [30]:
R_1 = np.random.normal(1.01, 0.03, 100)
returns = R_1[0]
assets = np.cumprod(R_1)[0] 

In [32]:
# Generate assets that are correlated with R_1
for i in range(1, N):
    R_i = R_1 + np.random.normal(0.001, 0.02, 100)
    returns = R_i[i] # Set each row of returns equal to the new R_i array
    assets = np.cumprod(R_i)[i]
    
mean_returns = [(np.mean(R) - 1)*100 for R in returns]
return_volatilities = [np.std(R) for R in returns]

TypeError: 'numpy.float64' object is not iterable